DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR (50) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS items;

CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    name VARCHAR (50) NOT NULL,
    float NUMERIC(3, 2) NOT NULL,
    rarity VARCHAR (50) NOT NULL,
    price NUMERIC(8, 2) NOT NULL,
    status VARCHAR (50) NOT NULL
);

ALTER TABLE users
ADD COLUMN balance NUMERIC(15, 2);